name = "remix-cloudflare-demo-maxim-shirshin"
type = "javascript"
workers_dev = true
account_id = "9a4b07d1292b8ac2f2b334e3ab71da57"
zone_id = "9d4844398fba046bd2dddc2601bba634"

[build]
command = "echo 'noop'"
watch_dir = "app"

[build.upload]
format = "service-worker"
